sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7aCXcETuDaRcgtHkob
    access-key-secret: LatetE8sMTUawSswsZX0kipd6D37RS
    bucket-name: ryan-take-out

  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx86c58cbf06494998
    secret: 357d6cfffd4bf4a2e6e2aa064ae68520
